/*
 * Per-tool display metadata: an MDI icon, a localized pretty name, and a
 * localized one-line tooltip for each ha_* tool. Used by the tool-call header.
 * Unknown tools fall back to a generic icon + a prettified id.
 */
import {
  mdiPuzzleOutline, mdiFloorPlan, mdiRobotOutline, mdiBackupRestore, mdiFileDocumentOutline,
  mdiTagMultipleOutline, mdiForumOutline, mdiViewDashboardOutline, mdiDevices, mdiBookOpenVariant,
  mdiShapeOutline, mdiPulse, mdiGraphOutline, mdiTuneVariant, mdiHistory, mdiPowerPlugOutline,
  mdiLabelOutline, mdiBookOpenOutline, mdiTextBoxOutline, mdiDelta, mdiNoteTextOutline, mdiBellOutline,
  mdiAccountGroupOutline, mdiClipboardListOutline, mdiDatabaseOutline, mdiRestart, mdiPaletteOutline,
  mdiScriptTextOutline, mdiFlashOutline, mdiCartOutline, mdiChartBar, mdiServerOutline, mdiNfcVariant,
  mdiCodeBraces, mdiFileCodeOutline, mdiMapMarkerRadiusOutline, mdiToolboxOutline,
  mdiConsole, mdiContentSaveOutline, mdiFileEditOutline, mdiFolderOutline, mdiMagnify, mdiFileSearchOutline, mdiFileDocumentOutline as mdiReadDoc,
} from "@mdi/js";
import { lang, type Lang } from "./i18n.js";

type L = Record<Lang, string>;
type Meta = { icon: string; label: L; desc: L };

const T: Record<string, Meta> = {
  ha_addons: { icon: mdiPuzzleOutline, label: { en: "Add-ons", da: "Tilføjelser", no: "Tillegg", sv: "Tillägg", de: "Add-ons" }, desc: { en: "Manage add-ons", da: "Administrér tilføjelser", no: "Administrer tillegg", sv: "Hantera tillägg", de: "Add-ons verwalten" } },
  ha_areas: { icon: mdiFloorPlan, label: { en: "Areas", da: "Områder", no: "Områder", sv: "Områden", de: "Bereiche" }, desc: { en: "Areas & floors", da: "Områder & etager", no: "Områder & etasjer", sv: "Områden & våningar", de: "Bereiche & Etagen" } },
  ha_automations: { icon: mdiRobotOutline, label: { en: "Automations", da: "Automatiseringer", no: "Automasjoner", sv: "Automationer", de: "Automationen" }, desc: { en: "Manage automations", da: "Administrér automatiseringer", no: "Administrer automasjoner", sv: "Hantera automationer", de: "Automationen verwalten" } },
  ha_backups: { icon: mdiBackupRestore, label: { en: "Backups", da: "Sikkerhedskopier", no: "Sikkerhetskopier", sv: "Säkerhetskopior", de: "Backups" }, desc: { en: "Create & restore backups", da: "Opret & gendan sikkerhedskopier", no: "Opprett & gjenopprett sikkerhetskopier", sv: "Skapa & återställ säkerhetskopior", de: "Backups erstellen & wiederherstellen" } },
  ha_blueprints: { icon: mdiFileDocumentOutline, label: { en: "Blueprints", da: "Blueprints", no: "Blueprints", sv: "Blueprints", de: "Blueprints" }, desc: { en: "Reusable automation templates", da: "Genbrugelige automatiserings-skabeloner", no: "Gjenbrukbare automasjonsmaler", sv: "Återanvändbara automationsmallar", de: "Wiederverwendbare Automations-Vorlagen" } },
  ha_categories: { icon: mdiTagMultipleOutline, label: { en: "Categories", da: "Kategorier", no: "Kategorier", sv: "Kategorier", de: "Kategorien" }, desc: { en: "Organize automations, scripts, scenes", da: "Organisér automatiseringer, scripts, scener", no: "Organiser automasjoner, skript, scener", sv: "Organisera automationer, skript, scener", de: "Automationen, Skripte, Szenen organisieren" } },
  ha_conversation: { icon: mdiForumOutline, label: { en: "Assist", da: "Assist", no: "Assist", sv: "Assist", de: "Assist" }, desc: { en: "Test the Assist voice agent", da: "Test Assist-stemmeagenten", no: "Test Assist-taleagenten", sv: "Testa Assist-röstagenten", de: "Assist-Sprachagent testen" } },
  ha_dashboards: { icon: mdiViewDashboardOutline, label: { en: "Dashboards", da: "Dashboards", no: "Dashbord", sv: "Dashboards", de: "Dashboards" }, desc: { en: "Manage dashboards & cards", da: "Administrér dashboards & kort", no: "Administrer dashbord & kort", sv: "Hantera dashboards & kort", de: "Dashboards & Karten verwalten" } },
  ha_devices: { icon: mdiDevices, label: { en: "Devices", da: "Enheder", no: "Enheter", sv: "Enheter", de: "Geräte" }, desc: { en: "Inspect & organize devices", da: "Inspicér & organisér enheder", no: "Inspiser & organiser enheter", sv: "Inspektera & organisera enheter", de: "Geräte prüfen & organisieren" } },
  ha_docs: { icon: mdiBookOpenVariant, label: { en: "Documentation", da: "Dokumentation", no: "Dokumentasjon", sv: "Dokumentation", de: "Dokumentation" }, desc: { en: "Look up integration docs", da: "Slå integrations-dokumentation op", no: "Slå opp integrasjonsdokumentasjon", sv: "Slå upp integrationsdokumentation", de: "Integrations-Dokumentation nachschlagen" } },
  ha_entities: { icon: mdiShapeOutline, label: { en: "Entities", da: "Entiteter", no: "Entiteter", sv: "Entiteter", de: "Entitäten" }, desc: { en: "Browse & inspect entities", da: "Gennemse & inspicér entiteter", no: "Bla gjennom & inspiser entiteter", sv: "Bläddra & inspektera entiteter", de: "Entitäten durchsuchen & prüfen" } },
  ha_events: { icon: mdiPulse, label: { en: "Events", da: "Hændelser", no: "Hendelser", sv: "Händelser", de: "Ereignisse" }, desc: { en: "Watch live events", da: "Overvåg live-hændelser", no: "Overvåk live-hendelser", sv: "Bevaka live-händelser", de: "Live-Ereignisse beobachten" } },
  ha_graph: { icon: mdiGraphOutline, label: { en: "Relationships", da: "Relationer", no: "Relasjoner", sv: "Relationer", de: "Beziehungen" }, desc: { en: "Entity relationship graph", da: "Entitets-relationsgraf", no: "Entitets-relasjonsgraf", sv: "Entitetsrelationsgraf", de: "Entitäts-Beziehungsgraph" } },
  ha_helpers: { icon: mdiTuneVariant, label: { en: "Helpers", da: "Hjælpere", no: "Hjelpere", sv: "Hjälpare", de: "Helfer" }, desc: { en: "Manage helpers (input_*, timers…)", da: "Administrér hjælpere (input_*, timere…)", no: "Administrer hjelpere (input_*, tidtakere…)", sv: "Hantera hjälpare (input_*, timers…)", de: "Helfer verwalten (input_*, Timer…)" } },
  ha_history: { icon: mdiHistory, label: { en: "History", da: "Historik", no: "Historikk", sv: "Historik", de: "Verlauf" }, desc: { en: "State history over time", da: "Tilstandshistorik over tid", no: "Tilstandshistorikk over tid", sv: "Tillståndshistorik över tid", de: "Zustandsverlauf über Zeit" } },
  ha_integrations: { icon: mdiPowerPlugOutline, label: { en: "Integrations", da: "Integrationer", no: "Integrasjoner", sv: "Integrationer", de: "Integrationen" }, desc: { en: "Manage integration entries", da: "Administrér integrationer", no: "Administrer integrasjoner", sv: "Hantera integrationer", de: "Integrationen verwalten" } },
  ha_labels: { icon: mdiLabelOutline, label: { en: "Labels", da: "Etiketter", no: "Etiketter", sv: "Etiketter", de: "Labels" }, desc: { en: "Manage labels", da: "Administrér etiketter", no: "Administrer etiketter", sv: "Hantera etiketter", de: "Labels verwalten" } },
  ha_logbook: { icon: mdiBookOpenOutline, label: { en: "Logbook", da: "Logbog", no: "Loggbok", sv: "Loggbok", de: "Logbuch" }, desc: { en: "Activity timeline", da: "Aktivitets-tidslinje", no: "Aktivitets-tidslinje", sv: "Aktivitetstidslinje", de: "Aktivitäts-Zeitachse" } },
  ha_logs: { icon: mdiTextBoxOutline, label: { en: "Logs", da: "Logfiler", no: "Logger", sv: "Loggar", de: "Protokolle" }, desc: { en: "System logs", da: "Systemlogfiler", no: "Systemlogger", sv: "Systemloggar", de: "Systemprotokolle" } },
  ha_mutations: { icon: mdiDelta, label: { en: "Change log", da: "Ændringslog", no: "Endringslogg", sv: "Ändringslogg", de: "Änderungsprotokoll" }, desc: { en: "Pre-change backups & changelog", da: "Backups før ændringer & log", no: "Sikkerhetskopier før endring & logg", sv: "Säkerhetskopior före ändring & logg", de: "Backups vor Änderungen & Protokoll" } },
  ha_notes: { icon: mdiNoteTextOutline, label: { en: "Notes", da: "Noter", no: "Notater", sv: "Anteckningar", de: "Notizen" }, desc: { en: "Agent notes on objects", da: "Agent-noter på objekter", no: "Agent-notater på objekter", sv: "Agent-anteckningar på objekt", de: "Agent-Notizen an Objekten" } },
  ha_notifications: { icon: mdiBellOutline, label: { en: "Notifications", da: "Notifikationer", no: "Varsler", sv: "Aviseringar", de: "Benachrichtigungen" }, desc: { en: "Persistent notifications", da: "Vedvarende notifikationer", no: "Vedvarende varsler", sv: "Beständiga aviseringar", de: "Dauerhafte Benachrichtigungen" } },
  ha_people: { icon: mdiAccountGroupOutline, label: { en: "People", da: "Personer", no: "Personer", sv: "Personer", de: "Personen" }, desc: { en: "People & presence", da: "Personer & tilstedeværelse", no: "Personer & tilstedeværelse", sv: "Personer & närvaro", de: "Personen & Anwesenheit" } },
  ha_policies: { icon: mdiClipboardListOutline, label: { en: "Conventions", da: "Konventioner", no: "Konvensjoner", sv: "Konventioner", de: "Konventionen" }, desc: { en: "Naming & organization policies", da: "Navngivnings- & organiseringspolitik", no: "Navngivnings- & organiseringsregler", sv: "Namngivnings- & organisationsregler", de: "Benennungs- & Organisationsregeln" } },
  ha_recorder: { icon: mdiDatabaseOutline, label: { en: "Recorder", da: "Optager", no: "Opptaker", sv: "Inspelare", de: "Recorder" }, desc: { en: "Recorder & statistics", da: "Optager & statistik", no: "Opptaker & statistikk", sv: "Inspelare & statistik", de: "Recorder & Statistik" } },
  ha_restart: { icon: mdiRestart, label: { en: "Restart / Reload", da: "Genstart", no: "Omstart", sv: "Omstart", de: "Neustart" }, desc: { en: "Restart or reload config", da: "Genstart eller genindlæs config", no: "Omstart eller last config på nytt", sv: "Starta om eller ladda om config", de: "Neustart oder Konfig neu laden" } },
  ha_scenes: { icon: mdiPaletteOutline, label: { en: "Scenes", da: "Scener", no: "Scener", sv: "Scener", de: "Szenen" }, desc: { en: "Manage & activate scenes", da: "Administrér & aktivér scener", no: "Administrer & aktiver scener", sv: "Hantera & aktivera scener", de: "Szenen verwalten & aktivieren" } },
  ha_scripts: { icon: mdiScriptTextOutline, label: { en: "Scripts", da: "Scripts", no: "Skript", sv: "Skript", de: "Skripte" }, desc: { en: "Manage & run scripts", da: "Administrér & kør scripts", no: "Administrer & kjør skript", sv: "Hantera & kör skript", de: "Skripte verwalten & ausführen" } },
  ha_services: { icon: mdiFlashOutline, label: { en: "Actions", da: "Handlinger", no: "Handlinger", sv: "Åtgärder", de: "Aktionen" }, desc: { en: "Call any service / action", da: "Kald en hvilken som helst handling", no: "Kall en hvilken som helst handling", sv: "Anropa valfri åtgärd", de: "Beliebige Aktion aufrufen" } },
  ha_shopping_list: { icon: mdiCartOutline, label: { en: "Shopping list", da: "Indkøbsliste", no: "Handleliste", sv: "Inköpslista", de: "Einkaufsliste" }, desc: { en: "Manage the shopping list", da: "Administrér indkøbslisten", no: "Administrer handlelisten", sv: "Hantera inköpslistan", de: "Einkaufsliste verwalten" } },
  ha_stats: { icon: mdiChartBar, label: { en: "Statistics", da: "Statistik", no: "Statistikk", sv: "Statistik", de: "Statistik" }, desc: { en: "Long-term statistics", da: "Langtidsstatistik", no: "Langtidsstatistikk", sv: "Långtidsstatistik", de: "Langzeitstatistik" } },
  ha_system: { icon: mdiServerOutline, label: { en: "System", da: "System", no: "System", sv: "System", de: "System" }, desc: { en: "System info & health", da: "Systeminfo & sundhed", no: "Systeminfo & helse", sv: "Systeminfo & hälsa", de: "Systeminfo & Zustand" } },
  ha_tags: { icon: mdiNfcVariant, label: { en: "Tags", da: "Tags", no: "Tagger", sv: "Taggar", de: "Tags" }, desc: { en: "NFC / QR tags", da: "NFC/QR-tags", no: "NFC/QR-tagger", sv: "NFC/QR-taggar", de: "NFC/QR-Tags" } },
  ha_template: { icon: mdiCodeBraces, label: { en: "Template", da: "Skabelon", no: "Mal", sv: "Mall", de: "Vorlage" }, desc: { en: "Render & test Jinja2", da: "Render & test Jinja2", no: "Render & test Jinja2", sv: "Rendera & testa Jinja2", de: "Jinja2 rendern & testen" } },
  ha_yaml: { icon: mdiFileCodeOutline, label: { en: "YAML config", da: "YAML-config", no: "YAML-config", sv: "YAML-config", de: "YAML-Konfig" }, desc: { en: "Edit YAML config", da: "Redigér YAML-config", no: "Rediger YAML-config", sv: "Redigera YAML-config", de: "YAML-Konfig bearbeiten" } },
  ha_zones: { icon: mdiMapMarkerRadiusOutline, label: { en: "Zones", da: "Zoner", no: "Soner", sv: "Zoner", de: "Zonen" }, desc: { en: "Geographic zones", da: "Geografiske zoner", no: "Geografiske soner", sv: "Geografiska zoner", de: "Geografische Zonen" } },
  web_search: { icon: mdiMagnify, label: { en: "Web search", da: "Websøgning", no: "Websøk", sv: "Webbsökning", de: "Websuche" }, desc: { en: "Search the live web", da: "Søg på det åbne web", no: "Søk på nettet", sv: "Sök på webben", de: "Im Web suchen" } },

  // Base agent tools
  bash: { icon: mdiConsole, label: { en: "Terminal", da: "Terminal", no: "Terminal", sv: "Terminal", de: "Terminal" }, desc: { en: "Run a terminal command", da: "Kør en terminal-kommando", no: "Kjør en terminal-kommando", sv: "Kör ett terminalkommando", de: "Terminal-Befehl ausführen" } },
  powershell: { icon: mdiConsole, label: { en: "Terminal", da: "Terminal", no: "Terminal", sv: "Terminal", de: "Terminal" }, desc: { en: "Run a terminal command", da: "Kør en terminal-kommando", no: "Kjør en terminal-kommando", sv: "Kör ett terminalkommando", de: "Terminal-Befehl ausführen" } },
  read: { icon: mdiReadDoc, label: { en: "Read file", da: "Læser fil", no: "Leser fil", sv: "Läser fil", de: "Datei lesen" }, desc: { en: "Read a file", da: "Læs en fil", no: "Les en fil", sv: "Läs en fil", de: "Eine Datei lesen" } },
  write: { icon: mdiContentSaveOutline, label: { en: "Write file", da: "Skriver fil", no: "Skriver fil", sv: "Skriver fil", de: "Datei schreiben" }, desc: { en: "Create or overwrite a file", da: "Opret eller overskriv en fil", no: "Opprett eller overskriv en fil", sv: "Skapa eller skriv över en fil", de: "Datei erstellen oder überschreiben" } },
  edit: { icon: mdiFileEditOutline, label: { en: "Edit file", da: "Redigerer fil", no: "Redigerer fil", sv: "Redigerar fil", de: "Datei bearbeiten" }, desc: { en: "Edit a file", da: "Redigér en fil", no: "Rediger en fil", sv: "Redigera en fil", de: "Eine Datei bearbeiten" } },
  ls: { icon: mdiFolderOutline, label: { en: "List folder", da: "Viser mappe", no: "Viser mappe", sv: "Visar mapp", de: "Ordner anzeigen" }, desc: { en: "List a directory", da: "Vis indholdet af en mappe", no: "Vis innholdet i en mappe", sv: "Visa innehållet i en mapp", de: "Verzeichnisinhalt anzeigen" } },
  grep: { icon: mdiMagnify, label: { en: "Search", da: "Søger", no: "Søker", sv: "Söker", de: "Suchen" }, desc: { en: "Search file contents", da: "Søg i filindhold", no: "Søk i filinnhold", sv: "Sök i filinnehåll", de: "Dateiinhalte durchsuchen" } },
  find: { icon: mdiFileSearchOutline, label: { en: "Find files", da: "Finder filer", no: "Finner filer", sv: "Hittar filer", de: "Dateien finden" }, desc: { en: "Find files by name", da: "Find filer ud fra navn", no: "Finn filer etter navn", sv: "Hitta filer efter namn", de: "Dateien nach Namen finden" } },
};

export function toolMeta(name: string): { icon: string; label: string; desc: string } {
  const m = T[name];
  if (!m) return { icon: mdiToolboxOutline, label: name.replace(/^ha_/, "").replace(/_/g, " "), desc: name };
  return { icon: m.icon, label: m.label[lang] ?? m.label.en, desc: m.desc[lang] ?? m.desc.en };
}
